const fs = require('fs');
const path = require('path');

/**
 * Generate CSV report for X or Z report data
 * @param {Object} reportData - Report data (same as for PDF)
 * @param {string} reportType - 'x_report' or 'z_report'
 * @returns {Object} CSV generation result
 */
async function generateCSV(reportData, reportType) {
  try {
    if (!reportData || typeof reportData !== 'object') {
      throw new Error('Invalid report data provided');
    }
    if (!reportType || typeof reportType !== 'string') {
      throw new Error('Invalid report type provided');
    }

    const reportsDir = path.join(__dirname, '../reports');
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `${reportType}-report-${timestamp}.csv`;
    const filePath = path.join(reportsDir, filename);

    // Build CSV content
    let csv = '';
    // Header
    csv += `${reportType.toUpperCase()} REPORT\n`;
    csv += `Date,${reportData.date || 'N/A'}\n`;
    csv += `Generated by,${reportData.generated_by || 'Unknown'}\n`;
    csv += `\n`;

    // Summary
    if (reportData.summary) {
      csv += 'SUMMARY\n';
      Object.entries(reportData.summary).forEach(([key, value]) => {
        csv += `${key},${value}\n`;
      });
      csv += '\n';
    }

    // Top Products
    if (reportData.top_products && reportData.top_products.length > 0) {
      csv += 'TOP PRODUCTS\n';
      csv += 'Name,Quantity\n';
      reportData.top_products.forEach(product => {
        csv += `${product.name},${product.qty}\n`;
      });
      csv += '\n';
    }

    // Transactions
    if (reportData.transactions && reportData.transactions.length > 0) {
      csv += 'TRANSACTIONS\n';
      csv += 'ID,Amount,Payment Method,Time\n';
      reportData.transactions.forEach(txn => {
        csv += `${txn.id},${txn.total},${txn.payment_method},${txn.created_at}\n`;
      });
      csv += '\n';
    }

    fs.writeFileSync(filePath, csv);
    return {
      success: true,
      filePath,
      filename
    };
  } catch (error) {
    throw new Error(`CSV generation failed: ${error.message}`);
  }
}

module.exports = {
  generateCSV
}; 