const fs = require("fs");
const path = require("path");

/**
 * Generate CSV report for X or Z report data as a single-row summary
 * @param {Object} reportData - Report data (same as for PDF)
 * @param {string} reportType - 'x_report' or 'z_report'
 * @returns {Object} CSV generation result
 */
async function generateCSV(reportData, reportType) {
	try {
		if (!reportData || typeof reportData !== "object") {
			throw new Error("Invalid report data provided");
		}
		if (!reportType || typeof reportType !== "string") {
			throw new Error("Invalid report type provided");
		}

		const reportsDir = path.join(__dirname, "../reports");
		if (!fs.existsSync(reportsDir)) {
			fs.mkdirSync(reportsDir, { recursive: true });
		}

		const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
		const filename = `${reportType}-report-${timestamp}.csv`;
		const filePath = path.join(reportsDir, filename);

		// Build horizontal summary CSV
		let headers = ["Type", "Date", "Generated By"];
		let values = [
			reportType.toUpperCase(),
			reportData.date || "N/A",
			reportData.generated_by || "Unknown",
		];

		// Add summary fields
		if (reportData.summary) {
			for (const [key, value] of Object.entries(reportData.summary)) {
				headers.push(
					key.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase())
				);
				values.push(value);
			}
		}

		// Add top products as columns
		if (reportData.top_products && reportData.top_products.length > 0) {
			reportData.top_products.forEach((product, idx) => {
				headers.push(`Top Product ${idx + 1}`);
				values.push(`${product.name} (${product.qty})`);
			});
		}

		// Write CSV
		const BOM = "\uFEFF";
		let csv = BOM + headers.join(",") + "\n" + values.join(",") + "\n";
		fs.writeFileSync(filePath, csv, { encoding: "utf8" });
		return {
			success: true,
			filePath,
			filename,
		};
	} catch (error) {
		throw new Error(`CSV generation failed: ${error.message}`);
	}
}

module.exports = {
	generateCSV,
};
