const fs = require('fs');
const path = require('path');

/**
 * Export GoBD-compliant data: transactions.csv, transaction_items.csv, metadata.txt
 * @param {Object} summary - Aggregated summary data (for metadata)
 * @param {Array} transactions - Array of transaction objects
 * @param {Array} items - Array of transaction item objects
 * @param {Object} [options] - Optional: { companyInfo, softwareInfo }
 * @returns {Object} Export result
 */
async function exportGoBD(summary, transactions, items, options = {}) {
  try {
    // Create exports directory if it doesn't exist
    const exportsDir = path.join(__dirname, '../exports');
    if (!fs.existsSync(exportsDir)) {
      fs.mkdirSync(exportsDir, { recursive: true });
    }
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const baseName = `gobd-export-${timestamp}`;

    // 1. Write transactions.csv
    const txHeaders = [
      'Transaction_ID', 'Timestamp', 'User', 'Payment_Method', 'Gross_Amount', 'Net_Amount', 'VAT_Amount', 'VAT_Rate', 'Correction', 'Cancelled', 'Customer_ID', 'Receipt_Number'
    ];
    const txRows = [txHeaders.join(',')];
    transactions.forEach(tx => {
      txRows.push([
        tx.id,
        tx.timestamp,
        tx.user_id || '',
        tx.payment_method,
        tx.total_amount,
        tx.net_amount || '',
        tx.vat_amount,
        tx.vat_rate || '',
        tx.correction_flag || '',
        tx.cancelled_flag || '',
        tx.customer_id || '',
        tx.receipt_number || ''
      ].join(','));
    });
    const txFile = path.join(exportsDir, `${baseName}-transactions.csv`);
    fs.writeFileSync(txFile, '\uFEFF' + txRows.join('\n'), { encoding: 'utf8' });

    // 2. Write transaction_items.csv
    const itemHeaders = [
      'Transaction_ID', 'Item_ID', 'Product_ID', 'Product_Name', 'Category', 'SKU', 'Quantity', 'Unit_Price', 'VAT_Rate', 'VAT_Amount', 'Total_Net', 'Total_Gross'
    ];
    const itemRows = [itemHeaders.join(',')];
    items.forEach(i => {
      itemRows.push([
        i.transaction_id,
        i.id,
        i.product_id,
        i.product_name || '',
        i.category || '',
        i.sku || '',
        i.quantity,
        i.unit_price,
        i.vat_rate || '',
        i.vat_amount || '',
        (i.unit_price * i.quantity).toFixed(2),
        ((i.unit_price * i.quantity) + (i.vat_amount || 0)).toFixed(2)
      ].join(','));
    });
    const itemFile = path.join(exportsDir, `${baseName}-transaction_items.csv`);
    fs.writeFileSync(itemFile, '\uFEFF' + itemRows.join('\n'), { encoding: 'utf8' });

    // 3. Write metadata.txt
    const metaFile = path.join(exportsDir, `${baseName}-metadata.txt`);
    const meta = [];
    meta.push('GoBD Export Metadata');
    meta.push('--------------------');
    meta.push(`Export Date       : ${summary.exportSummary.exportDate}`);
    meta.push(`Export Time       : ${summary.exportSummary.exportTime}`);
    meta.push(`Export Range      : ${summary.exportSummary.startDate} to ${summary.exportSummary.endDate}`);
    meta.push('');
    meta.push('Company Info:');
    meta.push('  Name: [TO BE FILLED]');
    meta.push('  Address: [TO BE FILLED]');
    meta.push('  Tax ID: [TO BE FILLED]');
    meta.push('');
    meta.push('Software Info:');
    meta.push('  Name: [TO BE FILLED]');
    meta.push('  Version: [TO BE FILLED]');
    meta.push('');
    meta.push('Export Methodology:');
    meta.push('  - Exported from POS system in compliance with GoBD (updated 2019).');
    meta.push('  - Includes all finalized transactions and items for the export date range.');
    meta.push('  - Cancellations and corrections are included if available.');
    meta.push('  - Data is formatted in CSV and timestamped in ISO 8601 format.');
    meta.push(`  - Export generated by user: user-1`);
    meta.push('');
    meta.push('Files Included:');
    meta.push('  - transactions.csv         (Header-level transaction data)');
    meta.push('  - transaction_items.csv    (Line-item breakdown of products sold)');
    meta.push('  - export_summary.txt       (Readable summary of totals and stats)');
    meta.push('  - metadata.txt             (This file)');
    meta.push('');
    meta.push('Summary:');
    meta.push(`  Total Transactions : ${summary.txnStats.totalTxns}`);
    meta.push(`  Total Items Sold   : ${summary.productSummary.totalItemsSold}`);
    meta.push(`  Gross Sales Total  : €${summary.financialSummary.totalGross.toFixed(2)}`);
    meta.push(`  VAT Collected      : €${summary.financialSummary.totalVAT.toFixed(2)}`);
    meta.push(`  Payment Methods    : Cash (${summary.paymentBreakdown.cashTxns}), Card (${summary.paymentBreakdown.cardTxns}), Other (${summary.paymentBreakdown.otherTxns})`);
    meta.push('');
    meta.push('System & Compliance Notes:');
    meta.push('  - Audit trail logging: ENABLED');
    meta.push('  - Digital corrections supported: NO');
    meta.push('  - Digital signatures applied: NO');
    meta.push('  - All data retained according to §147 AO (10 years)');
    fs.writeFileSync(metaFile, meta.join('\n'), { encoding: 'utf8' });

    return {
      success: true,
      files: [txFile, itemFile, metaFile],
      baseName
    };
  } catch (error) {
    throw new Error(`GoBD export failed: ${error.message}`);
  }
}

module.exports = {
  exportGoBD
};
