const fs = require('fs');
const path = require('path');

/**
 * Generate PDF report
 * @param {Object} reportData - Report data
 * @param {string} reportType - Type of report (X, Z, etc.)
 * @returns {Object} PDF generation result
 */
async function generatePDF(reportData, reportType) {
  try {
    // Create reports directory if it doesn't exist
    const reportsDir = path.join(__dirname, '../reports');
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    // Generate filename with proper extension
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `${reportType}-report-${timestamp}.txt`;
    const filePath = path.join(reportsDir, filename);

    // Generate formatted report content
    const reportContent = generatePDFContent(reportData, reportType);
    
    // Write to file
    fs.writeFileSync(filePath, reportContent, 'utf8');

    // Get file stats for download info
    const stats = fs.statSync(filePath);
    const fileSize = stats.size;

    return {
      success: true,
      filePath: filePath,
      filename: filename,
      fileSize: fileSize,
      downloadUrl: `file://${filePath}`,
      contentType: 'text/plain'
    };
  } catch (error) {
    throw new Error(`Report generation failed: ${error.message}`);
  }
}

/**
 * Generate PDF content
 * @param {Object} reportData - Report data
 * @param {string} reportType - Type of report
 * @returns {string} PDF content
 */
function generatePDFContent(reportData, reportType) {
  const date = new Date().toLocaleDateString();
  const time = new Date().toLocaleTimeString();
  
  let content = '';
  
  // Header
  content += '='.repeat(60) + '\n';
  content += `           ${reportType.toUpperCase()} REPORT\n`;
  content += '='.repeat(60) + '\n\n';
  
  // Report Info
  content += `Report Date:     ${reportData.date}\n`;
  content += `Generated:       ${date} at ${time}\n`;
  content += `Generated by:    ${reportData.generated_by}\n`;
  content += `Report Type:     ${reportType.toUpperCase()}\n\n`;
  
  // Summary Section
  if (reportData.summary) {
    content += '-'.repeat(60) + '\n';
    content += '                    SALES SUMMARY\n';
    content += '-'.repeat(60) + '\n';
    content += `Total Transactions:     ${reportData.summary.total_transactions || 0}\n`;
    content += `Total Sales:           €${(reportData.summary.total_sales || 0).toFixed(2)}\n`;
    content += `Cash Sales:            €${(reportData.summary.cash_sales || 0).toFixed(2)}\n`;
    content += `Card Sales:            €${(reportData.summary.card_sales || 0).toFixed(2)}\n`;
    content += `Other Sales:           €${(reportData.summary.other_sales || 0).toFixed(2)}\n`;
    
    if (reportData.summary.total_net) {
      content += '\n';
      content += `Net Amount:            €${reportData.summary.total_net.toFixed(2)}\n`;
      content += `VAT Amount:            €${reportData.summary.total_vat.toFixed(2)}\n`;
      content += `Gross Amount:          €${reportData.summary.total_gross.toFixed(2)}\n`;
    }
    content += '\n';
  }
  
  // Top Products Section
  if (reportData.top_products && reportData.top_products.length > 0) {
    content += '-'.repeat(60) + '\n';
    content += '                   TOP SELLING PRODUCTS\n';
    content += '-'.repeat(60) + '\n';
    reportData.top_products.forEach((product, index) => {
      content += `${(index + 1).toString().padStart(2)}. ${product.name.padEnd(30)} ${product.qty.toString().padStart(5)} units\n`;
    });
    content += '\n';
  }
  
  // Transactions Section (for Z reports)
  if (reportData.transactions && reportData.transactions.length > 0) {
    content += '-'.repeat(60) + '\n';
    content += '                    TRANSACTION DETAILS\n';
    content += '-'.repeat(60) + '\n';
    content += 'No.  Transaction ID          Amount    Payment    Time\n';
    content += '-'.repeat(60) + '\n';
    
    reportData.transactions.forEach((transaction, index) => {
      const transactionTime = new Date(transaction.created_at).toLocaleTimeString();
      content += `${(index + 1).toString().padStart(3)}.  ${transaction.id.padEnd(20)} €${transaction.total.toString().padStart(8)}  ${transaction.payment_method.padEnd(8)}  ${transactionTime}\n`;
    });
    content += '\n';
  }
  
  // Footer
  content += '='.repeat(60) + '\n';
  content += `End of ${reportType.toUpperCase()} Report\n`;
  content += '='.repeat(60) + '\n';
  
  return content;
}

module.exports = {
  generatePDF
};
