const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generate PDF report
 * @param {Object} reportData - Report data
 * @param {string} reportType - Type of report (X, Z, etc.)
 * @returns {Object} PDF generation result
 */
async function generatePDF(reportData, reportType) {
  try {
    // Validate input parameters
    if (!reportData || typeof reportData !== 'object') {
      throw new Error('Invalid report data provided');
    }
    
    if (!reportType || typeof reportType !== 'string') {
      throw new Error('Invalid report type provided');
    }
    
    const reportsDir = path.join(__dirname, '../reports');
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `${reportType}-report-${timestamp}.pdf`;
    const filePath = path.join(reportsDir, filename);

    // Create a new PDF document
    const doc = new PDFDocument();
    doc.pipe(fs.createWriteStream(filePath));

    // Add content to the PDF
    doc.fontSize(20).text(`${reportType} REPORT`, { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Generated: ${new Date().toLocaleString()}`);
    doc.text(`Date: ${reportData.date || 'N/A'}`);
    doc.text(`Generated by: ${reportData.generated_by || 'Unknown'}`);
    doc.moveDown();

    if (reportData.summary) {
      doc.fontSize(14).text('SUMMARY');
      Object.entries(reportData.summary).forEach(([key, value]) => {
        doc.text(`${key}: ${value}`);
      });
      doc.moveDown();
    }

    if (reportData.top_products && reportData.top_products.length > 0) {
      doc.fontSize(14).text('TOP PRODUCTS');
      reportData.top_products.forEach((product, idx) => {
        doc.text(`${idx + 1}. ${product.name}: ${product.qty} units`);
      });
      doc.moveDown();
    }

    if (reportData.transactions && reportData.transactions.length > 0) {
      doc.fontSize(14).text('TRANSACTIONS');
      reportData.transactions.forEach((transaction, idx) => {
        doc.text(
          `${idx + 1}. ID: ${transaction.id} | Amount: €${transaction.total} | Method: ${transaction.payment_method} | Time: ${transaction.created_at}`
        );
      });
    }

    doc.end();

    return {
      success: true,
      filePath: filePath,
      filename: filename
    };
  } catch (error) {
    throw new Error(`PDF generation failed: ${error.message}`);
  }
}

/**
 * Generate PDF content
 * @param {Object} reportData - Report data
 * @param {string} reportType - Type of report
 * @returns {string} PDF content
 */
function generatePDFContent(reportData, reportType) {
  const date = new Date().toLocaleDateString();
  const time = new Date().toLocaleTimeString();
  
  let content = `=== ${reportType} REPORT ===\n`;
  content += `Generated: ${date} at ${time}\n`;
  content += `Date: ${reportData.date}\n`;
  content += `Generated by: ${reportData.generated_by}\n\n`;
  
  if (reportData.summary) {
    content += `=== SUMMARY ===\n`;
    content += `Total Transactions: ${reportData.summary.total_transactions}\n`;
    content += `Total Sales: €${reportData.summary.total_sales?.toFixed(2) || '0.00'}\n`;
    content += `Cash Sales: €${reportData.summary.cash_sales?.toFixed(2) || '0.00'}\n`;
    content += `Card Sales: €${reportData.summary.card_sales?.toFixed(2) || '0.00'}\n`;
    content += `Other Sales: €${reportData.summary.other_sales?.toFixed(2) || '0.00'}\n`;
    
    if (reportData.summary.total_net) {
      content += `Net Amount: €${reportData.summary.total_net.toFixed(2)}\n`;
      content += `VAT Amount: €${reportData.summary.total_vat.toFixed(2)}\n`;
      content += `Gross Amount: €${reportData.summary.total_gross.toFixed(2)}\n`;
    }
    content += '\n';
  }
  
  if (reportData.top_products && reportData.top_products.length > 0) {
    content += `=== TOP PRODUCTS ===\n`;
    reportData.top_products.forEach((product, index) => {
      content += `${index + 1}. ${product.name}: ${product.qty} units\n`;
    });
    content += '\n';
  }
  
  if (reportData.transactions && reportData.transactions.length > 0) {
    content += `=== TRANSACTIONS ===\n`;
    reportData.transactions.forEach((transaction, index) => {
      content += `${index + 1}. ID: ${transaction.id} | Amount: €${transaction.total} | Method: ${transaction.payment_method} | Time: ${transaction.created_at}\n`;
    });
  }
  
  content += '\n=== END OF REPORT ===\n';
  
  return content;
}

module.exports = {
  generatePDF
};